Traceback (most recent call last):
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/run_ssd.py", line 603, in <module>
    sys.exit(main())
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/run_ssd.py", line 587, in main
    wait_for_mig_reconfiguration(gpu_config)
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/run_ssd.py", line 534, in wait_for_mig_reconfiguration
    raise RunTimeError("MIG reconfiguration failed ...")
NameError: name 'RunTimeError' is not defined
