Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 468, in websocket_call
    client = WSClient(configuration, url, headers, capture_all)
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 62, in __init__
    self.sock = create_websocket(configuration, url, headers)
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 452, in create_websocket
    websocket.connect(url, header=header)
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/lib/python3.9/site-packages/websocket/_handshake.py", line 80, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/lib/python3.9/site-packages/websocket/_handshake.py", line 165, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/run_ssd.py", line 604, in <module>
    sys.exit(main())
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/run_ssd.py", line 596, in main
    await_completion(opts)
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/run_ssd.py", line 359, in await_completion
    thanos_start = query_thanos.query_current_ts(thanos)
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/query_thanos.py", line 85, in query_current_ts
    return _do_query(thanos, "query", query="cluster:memory_usage:ratio")['result'][0]['value'][0]
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/query_thanos.py", line 77, in _do_query
    resp = exec_in_pod("nvidia-gpu-operator", thanos["pod_name"], curl_cmd)
  File "/home/kevin/openshift/matrix_benchmark/exec/mlperf/query_thanos.py", line 106, in exec_in_pod
    return k8s_stream(v1.connect_get_namespaced_pod_exec,
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_reqeust
    return api_method(*args, **kwargs)
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
    return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info
    return self.api_client.call_api(
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/kevin/.local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 474, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: Handshake status 500 Internal Server Error

